name: 'Broken Markdown URL Definitions'
description: 'Find all broken links in the files of a directory'
inputs:
  directory:
    description: 'Directory in which to to search for links'
    required: false
outputs:
  links:
    description: "New-line separated list of broken links"
    value: ${{ steps.broken-links.outputs.links }}
  status:
    description: "Status of the completed action (either `success` or `failure`)"
    value: ${{ steps.action-status.outputs.status }}
runs:
  using: "composite"
  steps:
    - run: |
        echo "Starting search for broken links in Markdown files..."
      shell: bash
    - id: broken-links
      run: ${{ github.action_path }}/broken_links.sh ${{ inputs.directory }}
      shell: bash
    - id: action-status
      run: |
        if [ ${{ steps.broken-links.outputs.links }} == '' ]
        then
            echo "::set-output name=status::success"
        else
            echo "::set-output name=status::failure"
        fi
      shell: bash
