# Workflow name:
name: Test Workflow

# Workflow triggers:
on:
  push:

# Workflow jobs:
jobs:
  check_markdown_links:
    # Define the type of virtual host machine on which to run the job:
    runs-on: ubuntu-latest

    # Define the sequence of job steps...
    steps:
      # Checkout the current branch:
      - uses: actions/checkout@v3
      # Run the command to check Markdown links:
      - id: broken-links
        uses: ./
        with:
          directory: fixtures
          exclude: https://github.com/stdlib-js/stdlib/tree/develop/lib/node_modules
      # Print out the results:
      - run: |
          echo "Broken links:"
          echo $FAILURES
          echo "Warnings:"
          echo $WARNINGS
          echo Status: ${{ steps.broken-links.outputs.status }}
          echo "All links:"
          echo $LINKS
        env:
          FAILURES: ${{ steps.broken-links.outputs.failures}}
          WARNINGS: ${{ steps.broken-links.outputs.warnings}}
          LINKS: ${{ steps.broken-links.outputs.all_links}}